
baseURL = "https://makdoudN.github.io/"
languageCode = 'en-us'
title = 'Blog'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "A Tech Blog"
# Enable MathJax support
math = true
# Appearance settings
theme = 'auto'

# Intro on main page, content is markdown
homeIntroTitle = 'Welcome ! '
homeIntroContent = """
I’m a French Data Scientist with a passion for tackling tasks—simple or complex—through data-driven approaches. 
My interests span Machine Learning, Bayesian Modeling, Causal Inference, and a lot related fields. 
Beyond the technical aspects, I enjoy exploring problem spaces through the lens of data and derive simple yet actionnable answers.
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/makdoud-nizam/"


[[params.social]]
name = "github"
url = "https://github.com/makdoudN"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'
[markup.goldmark]
[markup.goldmark.extensions]
    [markup.goldmark.extensions.passthrough]
    enable = true
    [markup.goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)'], ['$', '$']]

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"


